# Generated by Django 5.0.1 on 2024-02-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_rcd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='credit_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='credit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit_account_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='debit_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact_information',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
