# Generated by Django 5.0.1 on 2024-03-13 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_rcd', '0002_journalentry_credit_account_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='reference_id',
        ),
    ]
